<a href="https://colab.research.google.com/github/niva1303-droid/Python-for-DA_Numpy-and-Pandas/blob/main/Python_for_DA_Numpy_and_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Numpy Array Operations:**
**Scenario:** You are given a list of daily average temperatures (in degrees Celsius) recorded over two weeks. Your task is to use NumPy to analyze this data.

In [34]:
import numpy as np


In [35]:
# 1. Create a 1D NumPy Array:
# Create a 1D NumPy array named temperatures_w1 for Week 1 with the following values:

temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

In [36]:
# 2. Inspection and Properties:
# Inspect the shape, data type, and the number of elements in the array.
# Inspect the shape of the temperatures_w1 array.

print(temperatures_w1)

# This is a 1-dimensional NumPy array containing the temperatures recorded for 7 days.

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [37]:
print(type(temperatures_w1))

<class 'numpy.ndarray'>


In [38]:
print("Temperature Array:", temperatures_w1)
print("Shape:", temperatures_w1.shape)
print("Data Type:", temperatures_w1.dtype)
print("Number of Elements:", temperatures_w1.size)

Temperature Array: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Shape: (7,)
Data Type: float64
Number of Elements: 7


In [39]:
# 3. Array Operations:

# Convert the temperatures_w1 from Celsius to Fahrenheit using the formula:
# Fahrenheit = (Celsius * 9/5) + 32

temperatures_farenheit = (temperatures_w1 * 9/5) + 32

print(temperatures_farenheit)

[72.5  77.54 69.44 74.12 78.98 76.64 71.42]


In [40]:
# Find the maximum, minimum, and mean temperatures for the week.

print("Max Temperature: ", temperatures_w1.max())
print("Min Temperature: ", temperatures_w1.min())
print("Average Temperature: ", round(temperatures_w1.mean(), 2))

Max Temperature:  26.1
Min Temperature:  20.8
Average Temperature:  23.54


4. **Array Slicing and Indexing:**

● Extract the temperatures for the first three days of the week.

● Extract the temperatures for the weekend (last two days).

● Extract the temperatures for the middle three days of the week.

In [41]:
print("First Three Days: ", temperatures_w1[:3])
print("Weekend - Last Two Days: ", temperatures_w1[-2:])
print("Middle Three Days: ", temperatures_w1[2:5])

First Three Days:  [22.5 25.3 20.8]
Weekend - Last Two Days:  [24.8 21.9]
Middle Three Days:  [20.8 23.4 26.1]


5. **Create a 2D Array:**

Create a 2D NumPy array named temperatures where each row represents
temperatures for a different week:

★ Row 1: [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9] (Week 1)

★ Row 2: [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1] (Week 2)

In [42]:
temperatures = np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
                        [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]]
                        )
print(temperatures)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


6.** Inspect and Slice the 2D Array:**

● Inspect and print the shape, data type, and total number of elements in the
temperatures array.

● Extract the temperatures for each week and the weekends (last two days) for
both weeks.

In [43]:
print("Shape:", temperatures.shape)
print("Data Type:", temperatures.dtype)
print("Number of Elements:", temperatures.size)

Shape: (2, 7)
Data Type: float64
Number of Elements: 14


In [44]:
print("Week 1: ", temperatures[0])
print("Week 2: ", temperatures[1])
print("Weekends for both the weeks: ", temperatures[:, -2:])


Week 1:  [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Week 2:  [19.2 22.5 21.3 24.  23.5 22.8 20.1]
Weekends for both the weeks:  [[24.8 21.9]
 [22.8 20.1]]


#**Pandas Series:**

1. Creating Pandas Series:

● Create a Pandas Series named marks with the following data:

➢ Marks: 95, 92, 89, 85, 80

➢ Custom Indices: 'Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'

In [45]:
import pandas as pd

marks = pd.Series(
    [95, 92, 89, 85, 80],
    index = ['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)

print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


2. **Indexing and Slicing:**

● Use the integer index position to access the mark of the 1st rank student.

● Use the loc accessor to retrieve the marks of the top 3 ranks by specifying their index
labels.

● Use the iloc accessor to retrieve the mark of the 3rd-ranked student.

● Apply a boolean mask to filter the Series and retrieve the ranks where the marks are
greater than 90.

In [46]:
print("Mark of the 1st Rank Student: ", marks.iloc[0])

Mark of the 1st Rank Student:  95


In [47]:
marks.loc['Rank1':'Rank3']

,0
Rank1,95
Rank2,92
Rank3,89


In [48]:
print("3rd Rank Mark:", marks.iloc[2])

3rd Rank Mark: 89


In [49]:
marks>90


,0
Rank1,True
Rank2,True
Rank3,False
Rank4,False
Rank5,False


In [50]:
print(marks[marks>90])

Rank1    95
Rank2    92
dtype: int64


3.** Manipulating Series:**

● Modify the mark of the student with the 1st rank to 100.

● Remove the entry corresponding to the last rank from the Series.

● Compute the CGPA by dividing each mark in the Series by 10

In [51]:
marks.loc["Rank1"] = 100
print(marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64


In [52]:
marks = marks.drop("Rank5")
print(marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64


In [53]:
cgpa = marks / 10
print(cgpa)

Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


#**Pandas DataFrame:**

**1. Creating Pandas DataFrame:**

● Create a Pandas DataFrame named transactions with the following data:

➢TransactionID: 101, 102, 103, 104, 105, 106, 107, 108, 109, 110

➢ ProductCategory: 'Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing',
'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'

➢ Region: 'North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South',
'North'

➢ Amount: 200, 150, 300, 450, 200, 250, 300, 180, 350, 400

In [1]:
import pandas as pd

transactions = pd.DataFrame({
    "TransactionID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],

    "ProductCategory": [
        "Electronics", "Clothing", "Electronics", "Furniture", "Clothing",
        "Electronics", "Furniture", "Clothing", "Furniture", "Electronics"
    ],

    "Region": [
        "North", "South", "North", "East", "West",
        "North", "East", "West", "South", "North"
    ],

    "Amount": [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


**2. Data Exploration:**

● Display the transactions DataFrame and its basic information, including head, tail, shape, column names, and data types.





In [2]:
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [3]:
transactions.head()

,TransactionID,ProductCategory,Region,Amount
0,101,Electronics,North,200
1,102,Clothing,South,150
2,103,Electronics,North,300
3,104,Furniture,East,450
4,105,Clothing,West,200


In [4]:
transactions.tail()

,TransactionID,ProductCategory,Region,Amount
5,106,Electronics,North,250
6,107,Furniture,East,300
7,108,Clothing,West,180
8,109,Furniture,South,350
9,110,Electronics,North,400


In [6]:
transactions.shape

(10, 4)

In [7]:
transactions.columns

Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')

In [8]:
transactions.dtypes

,0
TransactionID,int64
ProductCategory,object
Region,object
Amount,int64


● Display only the 'ProductCategory' and 'Amount' columns.

In [9]:
transactions[["ProductCategory", "Amount"]]

,ProductCategory,Amount
0,Electronics,200
1,Clothing,150
2,Electronics,300
3,Furniture,450
4,Clothing,200
5,Electronics,250
6,Furniture,300
7,Clothing,180
8,Furniture,350
9,Electronics,400


In [10]:
# ● Retrieve the last 3 columns of the DataFrame using iloc or loc.

transactions.iloc[:, -3:]

,ProductCategory,Region,Amount
0,Electronics,North,200
1,Clothing,South,150
2,Electronics,North,300
3,Furniture,East,450
4,Clothing,West,200
5,Electronics,North,250
6,Furniture,East,300
7,Clothing,West,180
8,Furniture,South,350
9,Electronics,North,400


In [11]:
# ● Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.

transactions[
    (transactions["Region"] == "North") &
    (transactions["Amount"] > 200)
]

,TransactionID,ProductCategory,Region,Amount
2,103,Electronics,North,300
5,106,Electronics,North,250
9,110,Electronics,North,400


In [12]:
# ● Find the value counts for the 'ProductCategory' column

transactions["ProductCategory"].value_counts()

,count
ProductCategory,
Electronics,4
Clothing,3
Furniture,3


In [13]:
# ● Find the unique values in the 'Region' column

transactions["Region"].unique()

array(['North', 'South', 'East', 'West'], dtype=object)

In [14]:
# ● Group by 'Region' and find the mean amount for each region.

transactions.groupby("Region")["Amount"].mean()

,Amount
Region,
East,375.0
North,287.5
South,250.0
West,190.0


**3. Manipulating the DataFrame:**

In [15]:
# ● Modify the 'Amount' for the transaction with TransactionID 102 to 165.

transactions.loc[transactions["TransactionID"] == 102, "Amount"] = 165

In [16]:
transactions[transactions["TransactionID"] == 102]

,TransactionID,ProductCategory,Region,Amount
1,102,Clothing,South,165


In [17]:
# ● Add a new column 'Discount' by calculating 10% of the 'Amount'.

transactions["Discount"] = transactions["Amount"] * 0.10

In [18]:
transactions

,TransactionID,ProductCategory,Region,Amount,Discount
0,101,Electronics,North,200,20.0
1,102,Clothing,South,165,16.5
2,103,Electronics,North,300,30.0
3,104,Furniture,East,450,45.0
4,105,Clothing,West,200,20.0
5,106,Electronics,North,250,25.0
6,107,Furniture,East,300,30.0
7,108,Clothing,West,180,18.0
8,109,Furniture,South,350,35.0
9,110,Electronics,North,400,40.0


In [19]:
#● Remove the row with TransactionID 109.

transactions.drop(
    transactions[transactions["TransactionID"] == 109].index,
    inplace=True
)

In [20]:
transactions

,TransactionID,ProductCategory,Region,Amount,Discount
0,101,Electronics,North,200,20.0
1,102,Clothing,South,165,16.5
2,103,Electronics,North,300,30.0
3,104,Furniture,East,450,45.0
4,105,Clothing,West,200,20.0
5,106,Electronics,North,250,25.0
6,107,Furniture,East,300,30.0
7,108,Clothing,West,180,18.0
9,110,Electronics,North,400,40.0


In [21]:
# ● Delete the 'Discount' column from the DataFrame

transactions.drop(columns="Discount", inplace=True)

In [22]:
transactions

,TransactionID,ProductCategory,Region,Amount
0,101,Electronics,North,200
1,102,Clothing,South,165
2,103,Electronics,North,300
3,104,Furniture,East,450
4,105,Clothing,West,200
5,106,Electronics,North,250
6,107,Furniture,East,300
7,108,Clothing,West,180
9,110,Electronics,North,400
